spark.master                     spark://spark:7077
spark.submit.deployMode          cluster
spark.app.name                   TrafficAnalysisScala

# Resources
spark.driver.memory              1g
spark.driver.cores               1
spark.executor.memory            1g
spark.executor.cores             1
spark.executor.instances         2

# UI Configuration
spark.ui.port                    4040
spark.ui.enabled                 true
spark.eventLog.enabled           true
spark.eventLog.dir               hdfs://namenode:8020/spark-logs

# MongoDB Configuration (Default)
spark.mongodb.write.connection.uri mongodb://mongodb:27017/logs_db.metrics
spark.mongodb.output.uri           mongodb://mongodb:27017/logs_db.metrics

# Network (Important for Docker)
# In cluster mode, driver runs on a worker. 
# We need to ensure it binds to 0.0.0.0 so external mapping works.
spark.driver.bindAddress         0.0.0.0
spark.ui.bindAddress             0.0.0.0
